// <auto-generated />
namespace ClassifiedMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class localname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(localname));
        
        string IMigrationMetadata.Id
        {
            get { return "201701012126306_localname'"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
