// <auto-generated />
namespace ClassifiedMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class categoryPathadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryPathadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201701020951435_categoryPath added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
